### ISSUE TITLE
Optional vertx properties are not optional

### ISSUE THREAD

**Issue by ieugen** [rworsnop/vertx-beans#4]
Hello, 

The Readme mentions that the VertxOptions in application.properties are optional, but my appplication fails to start because of invalid number format when parsing one option. 

I'm using spring 4.1.9 and vertx 3.2.1 with vertx-beans 1.2.1 . It shouldnt be a big issue if the vertx options are properly documented, which they are not.

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'vertxOptions' defined in class io.vertxbeans.VertxBeans: Unsatisfied dependency expressed through constructor argument with index 0 of type [java.lang.Long]: : Failed to convert value of type [java.lang.String] to required type [java.lang.Long]; nested exception is java.lang.NumberFormatException: For input string: "${vertx.warning-exception-time:}"; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type [java.lang.String] to required type [java.lang.Long]; nested exception is java.lang.NumberFormatException: For input string: "${vertx.warning-exception-time:}"
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:464)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1117)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1012)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
    ... 27 more
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert value of type [java.lang.String] to required type [java.lang.Long]; nested exception is java.lang.NumberFormatException: For input string: "${vertx.warning-exception-time:}"
    at org.springframework.beans.TypeConverterSupport.doConvert(TypeConverterSupport.java:77)
    at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:47)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:962)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
    ... 41 more
Caused by: java.lang.NumberFormatException: For input string: "${vertx.warning-exception-time:}"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Long.parseLong(Long.java:578)
```

**Comment by ieugen** [comment]
I think it's an issue with the way defaults are passed: 

```
  @Value("${vertx.warning-exception-time:}") Long warningExceptionTime,
  @Value("${vertx.event-loop-pool-size:}") Integer eventLoopPoolSize,
  @Value("${vertx.max-event-loop-execution-time:}") Long maxEventLoopExecutionTime,
  @Value("${vertx.worker-pool-size:}") Integer workerPoolSize,
```

**Comment by rworsnop** [comment]
Can you create a reproducer? I've never seen this problem.
Note that the [example](https://github.com/rworsnop/vertx-beans-example) doesn't need to set these properties.

**Comment by ieugen** [comment]
I found an explanation. In Spring with Java Configuration you don't get a `PropertySourcesPlaceholderConfigurer` automatically. 

You have to add one like this:

```
  @Bean
   public static PropertySourcesPlaceholderConfigurer propertySourcesPlaceholderConfigurer() {
      return new PropertySourcesPlaceholderConfigurer();
   }
```

http://www.baeldung.com/2012/02/06/properties-with-spring/#java

**Comment by rworsnop** [comment]
Yeah, I thought it was probably something along those lines. I use Spring Boot, which sets up a lot of that kind of thing automatically.

**Comment by rworsnop** [comment]
Resolved here: https://github.com/rworsnop/vertx-beans/pull/5
